name: Docker Image CI

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Save version
      run: basename $GITHUB_REF >version.txt

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          lindex/http-rewrite
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
        labels: |
          org.opencontainers.image.title=http-rewrite
          org.opencontainers.image.description=HTTP Rewriting-Proxy
          org.opencontainers.image.source=https://github.com/AB-Lindex/http-rewrite
          org.opencontainers.image.url=https://github.com/AB-Lindex/http-rewrite
          org.opencontainers.image.licenses=MIT

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
